### ISSUE TITLE
Can't build with node v12.6.0/npm 6.12.0  

### ISSUE THREAD

**Issue by dlvovsky** [microsoft/BotFramework-Emulator#1948]
## Version
v4
## Describe the bug
Can't build using node v12.6.0/npm 6.12.0  
errors:
`../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object, v8::NonCopyablePersistentTraits<v8::Object> >'
    assert(persistent().IsNearDeath());
`

## To Reproduce
1- git checkout v4
2- npm i -g lerna@3.4.0 gulp@4.0.0 gulp-cli@2.0.1 webpack@4.8.x jest
3- lerna bootstrap --hoist
4- npm run build
## Expected behavior
Should build without error.
## Screenshots
None
## Additional context
None

[bug]

**Comment by tonyanziano** [comment]
Hi @dlvovsky ,

I assume that this is due to the fact that Electron doesn't support and ship with node 12+ until `v5.x.x`, and we are currently using version `v4.1.1` which is still on node `10.11.0`.

We do include a [`.node-version` file](https://github.com/microsoft/BotFramework-Emulator/blob/master/.node-version) in the root of the project to lock the user's node version to `v10.14.2` when inside the project. This file is honored by several node version managers such as:

[nvm](https://github.com/nvm-sh/nvm)
[avn](https://www.npmjs.com/package/avn)
[nodenv](https://github.com/nodenv/nodenv)

Until we upgrade the Electron version we are using to `v5.x.x+`, I'd recommend trying to use one of the above node version managers to build the project with the specified version (`v10.14.2`).

We should update the `CONTRIBUTING.md` doc so that other people do not run into this same problem.

**Comment by dlvovsky** [comment]
Many thanks for your response
