### ISSUE TITLE
Cannot find module 'https-proxy-agent'

### ISSUE THREAD

**Issue by sycq** [Microsoft/BotFramework-Emulator#1175]
## Version

4.2.0 - windows (env: 10/64bit)

## Describe the bug

After updating to 4.2.0 from 4.1.0, I got to have following error message on the initial connect to the local bot application.

`Cannot find module 'https-proxy-agent'`

logs
```
[11:33:01]Emulator listening on http://localhost:xxxxx
[11:33:01]ngrok not configured (only needed when connecting to remotely hosted bots)
[11:33:01]Connecting to bots hosted remotely
[11:33:01]Edit ngrok settings
[11:33:01]POST201directline.startConversation
[11:33:01]Cannot find module 'https-proxy-agent'
[11:33:01]Cannot find module 'https-proxy-agent'
```

## To Reproduce

1. Start a local bot server by `node index.js`, which listens http://localhost:3978/api/messages.
2. Connect to the endpoint without ngrok

## Expected behavior

Successfully connected to the server (or, Connection Refused, etc...).

## Additional context

Rolling back to the 4.1.0, this error does not happen.  
But Emulator updates itself automatically, so it is very unuseful.

[bug]

**Comment by tonyanziano** [comment]
@sycq Thanks for pointing this out! We are working on the fix and will hopefully have a new version out soon. I will update this thread.

**Comment by justinwilaby** [comment]
Fixed with #1176

**Comment by tonyanziano** [comment]
@sycq We have implemented the fix and published a new version **4.2.1** of the Emulator. Feel free to auto update to the new version via the app or grab it off [the releases page here.](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.2.1)

**Comment by sycq** [comment]
Thank you for your rapid action.
Now it works!

**Comment by vansh187** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/40709014/54519661-0be0a980-498d-11e9-9958-ecf57344691a.png)
can u tell me abou the error how to resolve
